# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: maestrano-connector-rails 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "maestrano-connector-rails"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pierre Berard"]
  s.date = "2015-11-26"
  s.description = "Maestrano is the next generation marketplace for SME applications. See https://maestrano.com for details."
  s.email = "pierre.berard@maestrano.com"
  s.executables = ["rails"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/controllers/maestrano/connector/rails/admin_controller.rb",
    "app/controllers/maestrano/connector/rails/application_controller.rb",
    "app/controllers/maestrano/connector/rails/home_controller.rb",
    "app/controllers/maestrano/connector/rails/maestrano/account/group_users_controller.rb",
    "app/controllers/maestrano/connector/rails/maestrano/account/groups_contoller.rb",
    "app/controllers/maestrano/connector/rails/maestrano/auth/saml_controller.rb",
    "app/controllers/maestrano/connector/rails/sessions_controller.rb",
    "app/helpers/maestrano/connector/rails/session_helper.rb",
    "app/jobs/maestrano/connector/rails/synchronization_job.rb",
    "app/models/maestrano/connector/rails/concerns/entity.rb",
    "app/models/maestrano/connector/rails/concerns/external.rb",
    "app/models/maestrano/connector/rails/entity.rb",
    "app/models/maestrano/connector/rails/external.rb",
    "app/models/maestrano/connector/rails/id_map.rb",
    "app/models/maestrano/connector/rails/organization.rb",
    "app/models/maestrano/connector/rails/synchronization.rb",
    "app/models/maestrano/connector/rails/user.rb",
    "app/models/maestrano/connector/rails/user_organization_rel.rb",
    "bin/rails",
    "config/routes.rb",
    "db/migrate/20151122162100_create_maestrano_connector_rails_users.rb",
    "db/migrate/20151122162414_create_maestrano_connector_rails_organizations.rb",
    "db/migrate/20151122162613_create_maestrano_connector_rails_user_organization_rels.rb",
    "db/migrate/20151122163325_create_maestrano_connector_rails_synchronizations.rb",
    "db/migrate/20151122163449_create_maestrano_connector_rails_id_maps.rb",
    "lib/generators/USAGE",
    "lib/generators/install_generator.rb",
    "lib/generators/templates/admin_index.html.erb",
    "lib/generators/templates/entity.rb",
    "lib/generators/templates/example_entity.rb",
    "lib/generators/templates/external.rb",
    "lib/generators/templates/home_index.html.erb",
    "lib/maestrano-connector-rails.rb",
    "lib/maestrano/connector/rails.rb",
    "maestrano-connector-rails.gemspec",
    "maestrano.png",
    "test/helper.rb",
    "test/test_maestrano-connector-rails.rb"
  ]
  s.homepage = "http://github.com/maestrano/maestrano-connector-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.7"
  s.summary = "Rails framework to build connector with Maestrano"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<maestrano-rails>, ["~> 0.12.0"])
      s.add_runtime_dependency(%q<hash_mapper>, ["~> 0.2.1"])
      s.add_runtime_dependency(%q<delayed_job_active_record>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<maestrano-rails>, ["~> 0.12.0"])
      s.add_dependency(%q<hash_mapper>, ["~> 0.2.1"])
      s.add_dependency(%q<delayed_job_active_record>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<maestrano-rails>, ["~> 0.12.0"])
    s.add_dependency(%q<hash_mapper>, ["~> 0.2.1"])
    s.add_dependency(%q<delayed_job_active_record>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

